#!/bin/bash
. ./funcion.sh
'controlerror'

#Muestra el menu general
function _menuPrincipal()
{  
    clear
	echo "------------------------"
    echo "------practica UF2------"
    echo "------------------------"
    echo
    echo "1) Performance"
    echo "2) Programación de tareas"
    echo "3) Backups"
    echo "4) Salir"
   
    echo
    echo -n "Indica una opcion: "
    read op
   
    case $op in
		1)
			clear
			'Performance'
			;;
		2)
			clear
			'Programación_de_tareas'
			;;
		3)
			clear
			'Backups'
			;;
		4)
			clear
			exit
			;;
		*)
			clear
			'_menuPrincipal'
			;;
	esac
}
#main
#'_menuPrincipal'
