#!/bin/bash
. ./menu.sh

function prueba() {
read -p "introduce una url: " url
if [ "$url" != "" ]
then
    ping -c 4 $url > /dev/null
    if [ "$?" == "0" ]
    then
        '_menuPrincipal'
    else
        echo "adios"
    fi
else
    echo "Pues si no me quires decir tu url peor para ti"
fi
}
#main
'prueba'
